z = str(input('Введите текст '))
x = str(input('Введите первый искомый символ x '))
y = str(input('Введите второй искомый символ y '))
x1 = z.count(x)
y1 = z.count(y)
print('x: ',x1,', ','y: ',y1,'.',sep='')