import numpy as np
a_A = np.array([[1,54],[1,6],[2,7]])
b_A = np.array([[1,7,8,],[4,2,9],[5,6,3]])

a_AT = a_A.transpose()
b_AT = b_A.transpose()
print('a.')
print('A: ')
print(a_A)
print('AT:')
print(a_AT)
print('b.')
print('A: ')
print(b_A)
print('AT:')
print(b_AT)
